FROM python:3.12

# install base packages
RUN apt-get update && apt-get install -y mariadb-client less curl wget vim locate iputils-ping ssh rsync
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN pip install --upgrade pip
RUN mkdir /project
WORKDIR /project
COPY manage.py /project/manage.py
COPY requirements.txt /project/requirements.txt
RUN pip3 install -r /project/requirements.txt